language: C
dist: trusty
compiler:
    - clang
    - gcc
before_install:
      - sudo pip2 install pytest pytest-cov rmtest redis
      - sudo apt-get install --allow-unauthenticated -qq clang
      - git clone -b 4.0.1 --depth 1 https://github.com/antirez/redis.git
      - cd redis
      - sudo make install
      - cd ..
script: "cd src && make all test"
